-- Booking invites (RSVP tokens)

DO $$
BEGIN
  CREATE TYPE app_v3."BookingInviteStatus" AS ENUM ('PENDING', 'ACCEPTED', 'DECLINED');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS app_v3.booking_invites (
  env text NOT NULL DEFAULT 'prod',
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  booking_id integer NOT NULL,
  organization_id integer NOT NULL,
  invited_by_user_id uuid NOT NULL,
  token text NOT NULL,
  target_name text,
  target_contact citext,
  message text,
  status app_v3."BookingInviteStatus" NOT NULL DEFAULT 'PENDING',
  responded_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT booking_invites_booking_fk
    FOREIGN KEY (booking_id) REFERENCES app_v3.bookings(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_invites_org_fk
    FOREIGN KEY (organization_id) REFERENCES app_v3.organizations(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_invites_invited_by_fk
    FOREIGN KEY (invited_by_user_id) REFERENCES app_v3.profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_invites_token_uq UNIQUE (token)
);

CREATE INDEX IF NOT EXISTS booking_invites_booking_idx ON app_v3.booking_invites(booking_id);
CREATE INDEX IF NOT EXISTS booking_invites_org_idx ON app_v3.booking_invites(organization_id);
CREATE INDEX IF NOT EXISTS booking_invites_status_idx ON app_v3.booking_invites(status);
CREATE INDEX IF NOT EXISTS booking_invites_env_idx ON app_v3.booking_invites(env);

ALTER TABLE app_v3.booking_invites ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'app_v3' AND tablename = 'booking_invites' AND policyname = 'env_isolation'
  ) THEN
    CREATE POLICY env_isolation ON app_v3.booking_invites
      USING (env = current_setting('app.env', true))
      WITH CHECK (env = current_setting('app.env', true));
  END IF;
END $$;
