export const DASHBOARD_SHELL_PADDING = "px-4 md:px-6 lg:px-8";
export const DASHBOARD_CARD = "theme-surface";
export const DASHBOARD_MUTED = "text-white/80";
export const DASHBOARD_HEADING = "text-lg font-semibold text-white";
export const DASHBOARD_SUBHEADING = "text-sm text-white/78";
export const DASHBOARD_SKELETON = "animate-pulse rounded-xl border border-white/10 orya-skeleton-surface"; export const DASHBOARD_TITLE = "sr-only";
export const DASHBOARD_LABEL = "text-[11px] uppercase tracking-[0.22em] text-white/70"; export const CTA_PRIMARY = "inline-flex items-center gap-2 rounded-full border border-[#22D3EE]/55 bg-[#22D3EE]/18 px-6 py-2.5 text-sm font-semibold text-white transition hover:border-[#22D3EE]/75 hover:bg-[#22D3EE]/24 hover: focus:outline-none focus:ring-2 focus:ring-[#22D3EE]/65";
export const CTA_GHOST = "inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/0 px-4 py-2 text-sm text-white/90 hover:border-[#22D3EE]/45 hover:bg-[#22D3EE]/12 transition focus:outline-none focus:ring-2 focus:ring-[#22D3EE]/45";
export const CTA_SECONDARY = CTA_GHOST;
export const CTA_DANGER = "inline-flex items-center gap-2 rounded-full border border-red-400/60 bg-white/[0.04] px-3 py-1.5 text-[12px] font-semibold text-red-50 hover:brightness-110 transition";
export const CTA_NEUTRAL = "inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-[12px] text-white hover:border-[#22D3EE]/45 hover:bg-[#22D3EE]/12 transition";
export const CTA_SUCCESS = "inline-flex items-center gap-2 rounded-full border border-emerald-300/60 bg-white/[0.04] px-4 py-1.5 text-[12px] font-semibold text-emerald-50 hover:brightness-110 transition"; export const CTA_PRIMARY_CLEAN = "inline-flex items-center justify-center gap-2 rounded-full border border-[#22D3EE]/55 bg-[#22D3EE]/16 px-5 py-2 text-sm font-semibold text-white transition-colors hover:bg-[#22D3EE]/24 focus:outline-none focus:ring-2 focus:ring-[#22D3EE]/60";
export const CTA_SECONDARY_CLEAN = "inline-flex items-center justify-center gap-2 rounded-full border border-white/28 bg-white/[0.04] px-4 py-2 text-sm font-medium text-white/92 transition-colors hover:bg-white/[0.08] focus:outline-none focus:ring-2 focus:ring-white/32";
export const CTA_DANGER_CLEAN = "inline-flex items-center justify-center gap-2 rounded-full border border-red-300/60 bg-red-500/14 px-4 py-2 text-sm font-semibold text-red-100 transition-colors hover:bg-red-500/20 focus:outline-none focus:ring-2 focus:ring-red-300/55";
