ALTER TABLE app_v3.crm_contact_padel
  ADD COLUMN IF NOT EXISTS preferred_time_bucket TEXT,
  ADD COLUMN IF NOT EXISTS off_peak_ratio_30d DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reservation_count_90d INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS lesson_count_90d INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tournament_count_90d INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS avg_spend_per_session_cents_90d INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_no_show_at TIMESTAMPTZ(6);
