DO $$
BEGIN
  CREATE TYPE app_v3."ReservationCategoryDomain" AS ENUM ('COURT', 'CLASS', 'SERVICE');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END
$$;

CREATE TABLE IF NOT EXISTS app_v3.reservation_categories (
  env             text NOT NULL DEFAULT 'prod',
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id integer NOT NULL,
  domain          app_v3."ReservationCategoryDomain" NOT NULL,
  slug            text NOT NULL,
  label           text NOT NULL,
  is_active       boolean NOT NULL DEFAULT true,
  sort_order      integer NOT NULL DEFAULT 0,
  created_at      timestamptz(6) NOT NULL DEFAULT now(),
  updated_at      timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT reservation_categories_org_fk
    FOREIGN KEY (organization_id)
    REFERENCES app_v3.organizations(id)
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS reservation_categories_org_domain_slug_unique
  ON app_v3.reservation_categories (organization_id, domain, slug);

CREATE INDEX IF NOT EXISTS reservation_categories_org_domain_active_idx
  ON app_v3.reservation_categories (organization_id, domain, is_active);

ALTER TABLE app_v3.services
  ADD COLUMN IF NOT EXISTS category_id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'services_category_id_fkey'
  ) THEN
    ALTER TABLE app_v3.services
      ADD CONSTRAINT services_category_id_fkey
      FOREIGN KEY (category_id)
      REFERENCES app_v3.reservation_categories(id)
      ON DELETE SET NULL;
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS services_category_idx
  ON app_v3.services (category_id);

CREATE TABLE IF NOT EXISTS app_v3.court_booking_configs (
  env                 text NOT NULL DEFAULT 'prod',
  id                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id     integer NOT NULL,
  court_id            integer NOT NULL,
  backing_service_id  integer NOT NULL,
  category_id         integer NULL,
  display_name        text NOT NULL,
  display_description text NULL,
  cover_image_url     text NULL,
  is_active           boolean NOT NULL DEFAULT true,
  created_at          timestamptz(6) NOT NULL DEFAULT now(),
  updated_at          timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT court_booking_configs_org_fk
    FOREIGN KEY (organization_id)
    REFERENCES app_v3.organizations(id)
    ON DELETE CASCADE,
  CONSTRAINT court_booking_configs_court_fk
    FOREIGN KEY (court_id)
    REFERENCES app_v3.padel_club_courts(id)
    ON DELETE CASCADE,
  CONSTRAINT court_booking_configs_service_fk
    FOREIGN KEY (backing_service_id)
    REFERENCES app_v3.services(id)
    ON DELETE CASCADE,
  CONSTRAINT court_booking_configs_category_fk
    FOREIGN KEY (category_id)
    REFERENCES app_v3.reservation_categories(id)
    ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS court_booking_configs_court_unique
  ON app_v3.court_booking_configs (court_id);

CREATE INDEX IF NOT EXISTS court_booking_configs_org_active_idx
  ON app_v3.court_booking_configs (organization_id, is_active);

CREATE INDEX IF NOT EXISTS court_booking_configs_org_service_idx
  ON app_v3.court_booking_configs (organization_id, backing_service_id);

CREATE INDEX IF NOT EXISTS court_booking_configs_category_idx
  ON app_v3.court_booking_configs (category_id);

WITH org_seed AS (
  SELECT DISTINCT s.organization_id
  FROM app_v3.services s
  UNION
  SELECT DISTINCT c.organization_id
  FROM app_v3.padel_clubs c
),
default_categories AS (
  SELECT
    organization_id,
    domain,
    slug,
    label,
    sort_order
  FROM org_seed
  CROSS JOIN (
    VALUES
      ('COURT'::app_v3."ReservationCategoryDomain", 'campo-padel', 'Reserva de Campo', 10),
      ('CLASS'::app_v3."ReservationCategoryDomain", 'aulas', 'Aulas', 20),
      ('SERVICE'::app_v3."ReservationCategoryDomain", 'servicos', 'Serviços', 30)
  ) AS defaults(domain, slug, label, sort_order)
),
service_category_seed AS (
  SELECT DISTINCT
    s.organization_id,
    CASE
      WHEN s.kind = 'COURT' THEN 'COURT'::app_v3."ReservationCategoryDomain"
      WHEN s.kind = 'CLASS' THEN 'CLASS'::app_v3."ReservationCategoryDomain"
      ELSE 'SERVICE'::app_v3."ReservationCategoryDomain"
    END AS domain,
    CASE
      WHEN s.kind = 'COURT' THEN 'campo-padel'
      WHEN s.kind = 'CLASS' THEN 'aulas'
      WHEN lower(COALESCE(NULLIF(btrim(s.category_tag), ''), '')) IN ('aulas', 'aula', 'lesson', 'lessons', 'class', 'classes', 'treino', 'treinos') THEN 'aulas'
      WHEN lower(COALESCE(NULLIF(btrim(s.category_tag), ''), '')) IN ('padel', 'paddle', 'campo', 'campos', 'court', 'courts', 'reserva-campo', 'reserva-de-campo') THEN 'campo-padel'
      WHEN COALESCE(NULLIF(btrim(s.category_tag), ''), '') <> '' THEN
        left(
          regexp_replace(lower(btrim(s.category_tag)), '[^a-z0-9]+', '-', 'g'),
          60
        )
      ELSE 'servicos'
    END AS slug,
    CASE
      WHEN s.kind = 'COURT' THEN 'Reserva de Campo'
      WHEN s.kind = 'CLASS' THEN 'Aulas'
      WHEN lower(COALESCE(NULLIF(btrim(s.category_tag), ''), '')) IN ('aulas', 'aula', 'lesson', 'lessons', 'class', 'classes', 'treino', 'treinos') THEN 'Aulas'
      WHEN lower(COALESCE(NULLIF(btrim(s.category_tag), ''), '')) IN ('padel', 'paddle', 'campo', 'campos', 'court', 'courts', 'reserva-campo', 'reserva-de-campo') THEN 'Reserva de Campo'
      WHEN COALESCE(NULLIF(btrim(s.category_tag), ''), '') <> '' THEN left(btrim(s.category_tag), 80)
      ELSE 'Serviços'
    END AS label,
    40 AS sort_order
  FROM app_v3.services s
)
INSERT INTO app_v3.reservation_categories (
  organization_id,
  domain,
  slug,
  label,
  sort_order,
  created_at,
  updated_at
)
SELECT
  seed.organization_id,
  seed.domain,
  CASE
    WHEN seed.slug IS NULL OR btrim(seed.slug) = '' THEN 'servicos'
    ELSE btrim(seed.slug)
  END AS slug,
  CASE
    WHEN seed.label IS NULL OR btrim(seed.label) = '' THEN 'Serviços'
    ELSE btrim(seed.label)
  END AS label,
  seed.sort_order,
  now(),
  now()
FROM (
  SELECT * FROM default_categories
  UNION
  SELECT * FROM service_category_seed
) AS seed
ON CONFLICT (organization_id, domain, slug) DO NOTHING;

WITH service_slug AS (
  SELECT
    s.id AS service_id,
    s.organization_id,
    CASE
      WHEN s.kind = 'COURT' THEN 'COURT'::app_v3."ReservationCategoryDomain"
      WHEN s.kind = 'CLASS' THEN 'CLASS'::app_v3."ReservationCategoryDomain"
      ELSE 'SERVICE'::app_v3."ReservationCategoryDomain"
    END AS domain,
    CASE
      WHEN s.kind = 'COURT' THEN 'campo-padel'
      WHEN s.kind = 'CLASS' THEN 'aulas'
      WHEN lower(COALESCE(NULLIF(btrim(s.category_tag), ''), '')) IN ('aulas', 'aula', 'lesson', 'lessons', 'class', 'classes', 'treino', 'treinos') THEN 'aulas'
      WHEN lower(COALESCE(NULLIF(btrim(s.category_tag), ''), '')) IN ('padel', 'paddle', 'campo', 'campos', 'court', 'courts', 'reserva-campo', 'reserva-de-campo') THEN 'campo-padel'
      WHEN COALESCE(NULLIF(btrim(s.category_tag), ''), '') <> '' THEN
        left(
          regexp_replace(lower(btrim(s.category_tag)), '[^a-z0-9]+', '-', 'g'),
          60
        )
      ELSE 'servicos'
    END AS slug
  FROM app_v3.services s
),
category_match AS (
  SELECT
    svc.service_id,
    cat.id AS category_id
  FROM service_slug svc
  JOIN app_v3.reservation_categories cat
    ON cat.organization_id = svc.organization_id
   AND cat.domain = svc.domain
   AND cat.slug = CASE
     WHEN svc.slug IS NULL OR btrim(svc.slug) = '' THEN 'servicos'
     ELSE btrim(svc.slug)
   END
)
UPDATE app_v3.services s
SET category_id = match.category_id
FROM category_match match
WHERE s.id = match.service_id
  AND s.category_id IS DISTINCT FROM match.category_id;

WITH fallback_category AS (
  SELECT
    s.id AS service_id,
    cat.id AS category_id
  FROM app_v3.services s
  JOIN app_v3.reservation_categories cat
    ON cat.organization_id = s.organization_id
   AND cat.slug = CASE
     WHEN s.kind = 'COURT' THEN 'campo-padel'
     WHEN s.kind = 'CLASS' THEN 'aulas'
     ELSE 'servicos'
   END
   AND cat.domain = CASE
     WHEN s.kind = 'COURT' THEN 'COURT'::app_v3."ReservationCategoryDomain"
     WHEN s.kind = 'CLASS' THEN 'CLASS'::app_v3."ReservationCategoryDomain"
     ELSE 'SERVICE'::app_v3."ReservationCategoryDomain"
   END
)
UPDATE app_v3.services s
SET category_id = f.category_id
FROM fallback_category f
WHERE s.id = f.service_id
  AND s.category_id IS NULL;

WITH courts AS (
  SELECT
    c.id AS court_id,
    c.name,
    c.description,
    c.is_active,
    club.organization_id
  FROM app_v3.padel_club_courts c
  JOIN app_v3.padel_clubs club
    ON club.id = c.padel_club_id
  WHERE c.deleted_at IS NULL
    AND club.deleted_at IS NULL
),
service_court_candidates AS (
  SELECT
    s.organization_id,
    rr.court_id,
    s.id AS service_id
  FROM app_v3.services s
  JOIN app_v3.service_resources sr
    ON sr.service_id = s.id
  JOIN app_v3.reservation_resources rr
    ON rr.id = sr.resource_id
  WHERE s.kind = 'COURT'
    AND s.is_active = true
    AND rr.court_id IS NOT NULL
    AND rr.is_active = true
),
ranked_candidates AS (
  SELECT
    organization_id,
    court_id,
    service_id,
    row_number() OVER (PARTITION BY organization_id, court_id ORDER BY service_id ASC) AS rn,
    count(*) OVER (PARTITION BY organization_id, court_id) AS candidate_count
  FROM service_court_candidates
),
resolved_service AS (
  SELECT
    organization_id,
    court_id,
    service_id
  FROM ranked_candidates
  WHERE rn = 1
    AND candidate_count = 1
),
fallback_service AS (
  SELECT
    s.organization_id,
    min(s.id) AS service_id
  FROM app_v3.services s
  WHERE s.kind = 'COURT'
    AND s.is_active = true
  GROUP BY s.organization_id
),
chosen_mapping AS (
  SELECT
    courts.organization_id,
    courts.court_id,
    COALESCE(resolved_service.service_id, fallback_service.service_id) AS service_id,
    resolved_service.service_id IS NOT NULL AS has_unique_mapping,
    courts.name,
    courts.description,
    courts.is_active
  FROM courts
  LEFT JOIN resolved_service
    ON resolved_service.organization_id = courts.organization_id
   AND resolved_service.court_id = courts.court_id
  LEFT JOIN fallback_service
    ON fallback_service.organization_id = courts.organization_id
  WHERE COALESCE(resolved_service.service_id, fallback_service.service_id) IS NOT NULL
)
INSERT INTO app_v3.court_booking_configs (
  organization_id,
  court_id,
  backing_service_id,
  category_id,
  display_name,
  display_description,
  cover_image_url,
  is_active,
  created_at,
  updated_at
)
SELECT
  chosen.organization_id,
  chosen.court_id,
  chosen.service_id,
  svc.category_id,
  COALESCE(NULLIF(btrim(chosen.name), ''), 'Campo #' || chosen.court_id::text) AS display_name,
  NULLIF(btrim(chosen.description), '') AS display_description,
  svc.cover_image_url,
  CASE
    WHEN chosen.has_unique_mapping THEN chosen.is_active
    ELSE false
  END AS is_active,
  now(),
  now()
FROM chosen_mapping chosen
JOIN app_v3.services svc
  ON svc.id = chosen.service_id
ON CONFLICT (court_id) DO UPDATE
SET
  organization_id = EXCLUDED.organization_id,
  backing_service_id = EXCLUDED.backing_service_id,
  category_id = EXCLUDED.category_id,
  display_name = EXCLUDED.display_name,
  display_description = EXCLUDED.display_description,
  cover_image_url = EXCLUDED.cover_image_url,
  is_active = EXCLUDED.is_active,
  updated_at = now();
