DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'BookingSplitMode'
      AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."BookingSplitMode" AS ENUM ('SPLIT_GARANTIDO');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'BookingSplitRailState'
      AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."BookingSplitRailState" AS ENUM ('HOLD_CAPTURE', 'OFFSESSION_PI', 'DEBT');
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'BookingSplitCaptureBeforeSource'
      AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."BookingSplitCaptureBeforeSource" AS ENUM (
      'GATEWAY_EXPLICIT',
      'CANONICAL_COMPUTED_TABLE'
    );
  END IF;
END$$;

ALTER TABLE app_v3.booking_splits
  ADD COLUMN IF NOT EXISTS split_mode app_v3."BookingSplitMode" NOT NULL DEFAULT 'SPLIT_GARANTIDO',
  ADD COLUMN IF NOT EXISTS rail_state app_v3."BookingSplitRailState" NOT NULL DEFAULT 'HOLD_CAPTURE',
  ADD COLUMN IF NOT EXISTS capture_before_at timestamptz(6),
  ADD COLUMN IF NOT EXISTS capture_before_source app_v3."BookingSplitCaptureBeforeSource" NOT NULL DEFAULT 'CANONICAL_COMPUTED_TABLE',
  ADD COLUMN IF NOT EXISTS retry_until_at timestamptz(6),
  ADD COLUMN IF NOT EXISTS settled_at timestamptz(6),
  ADD COLUMN IF NOT EXISTS debt_opened_at timestamptz(6);

CREATE INDEX IF NOT EXISTS booking_splits_rail_state_idx
  ON app_v3.booking_splits (rail_state);

CREATE INDEX IF NOT EXISTS booking_splits_deadline_idx
  ON app_v3.booking_splits (deadline_at);

CREATE INDEX IF NOT EXISTS booking_splits_retry_until_idx
  ON app_v3.booking_splits (retry_until_at);

CREATE TABLE IF NOT EXISTS app_v3.booking_split_debts (
  env text NOT NULL DEFAULT 'prod',
  id integer GENERATED BY DEFAULT AS IDENTITY,
  split_id integer NOT NULL,
  booking_id integer NOT NULL,
  organization_id integer NOT NULL,
  currency text NOT NULL DEFAULT 'EUR',
  outstanding_cents integer NOT NULL,
  opened_at timestamptz(6) NOT NULL DEFAULT now(),
  settled_at timestamptz(6),
  metadata jsonb DEFAULT '{}',
  CONSTRAINT booking_split_debts_pkey PRIMARY KEY (id),
  CONSTRAINT booking_split_debts_split_unique UNIQUE (split_id),
  CONSTRAINT booking_split_debts_split_fk
    FOREIGN KEY (split_id) REFERENCES app_v3.booking_splits(id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_split_debts_booking_fk
    FOREIGN KEY (booking_id) REFERENCES app_v3.bookings(id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_split_debts_organization_fk
    FOREIGN KEY (organization_id) REFERENCES app_v3.organizations(id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS booking_split_debts_org_idx
  ON app_v3.booking_split_debts (organization_id);

CREATE INDEX IF NOT EXISTS booking_split_debts_booking_idx
  ON app_v3.booking_split_debts (booking_id);

CREATE INDEX IF NOT EXISTS booking_split_debts_opened_at_idx
  ON app_v3.booking_split_debts (opened_at);

CREATE TABLE IF NOT EXISTS app_v3.booking_split_settlement_snapshots (
  env text NOT NULL DEFAULT 'prod',
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  split_id integer NOT NULL,
  booking_id integer NOT NULL,
  organization_id integer NOT NULL,
  snapshot_hash text NOT NULL,
  snapshot jsonb NOT NULL,
  computed_at timestamptz(6) NOT NULL,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT booking_split_settlement_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT booking_split_settlement_snapshots_split_unique UNIQUE (split_id),
  CONSTRAINT booking_split_settlement_snapshots_split_fk
    FOREIGN KEY (split_id) REFERENCES app_v3.booking_splits(id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_split_settlement_snapshots_booking_fk
    FOREIGN KEY (booking_id) REFERENCES app_v3.bookings(id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_split_settlement_snapshots_organization_fk
    FOREIGN KEY (organization_id) REFERENCES app_v3.organizations(id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS booking_split_settlement_snapshots_org_idx
  ON app_v3.booking_split_settlement_snapshots (organization_id);

CREATE INDEX IF NOT EXISTS booking_split_settlement_snapshots_booking_idx
  ON app_v3.booking_split_settlement_snapshots (booking_id);

CREATE INDEX IF NOT EXISTS booking_split_settlement_snapshots_computed_idx
  ON app_v3.booking_split_settlement_snapshots (computed_at);
