-- D14 Multi-Organizações (OrganizationGroup + GroupMember)

CREATE TABLE IF NOT EXISTS app_v3.organization_groups (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE app_v3.organizations ADD COLUMN IF NOT EXISTS group_id integer;

INSERT INTO app_v3.organization_groups (id, created_at, updated_at)
SELECT o.id, now(), now()
FROM app_v3.organizations o
WHERE o.group_id IS NULL
ON CONFLICT (id) DO NOTHING;

UPDATE app_v3.organizations
SET group_id = id
WHERE group_id IS NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'organizations_group_id_fkey'
  ) THEN
    ALTER TABLE app_v3.organizations
      ADD CONSTRAINT organizations_group_id_fkey
      FOREIGN KEY (group_id)
      REFERENCES app_v3.organization_groups(id)
      ON DELETE RESTRICT;
  END IF;
END $$;

ALTER TABLE app_v3.organizations
  ALTER COLUMN group_id SET NOT NULL;

CREATE TABLE IF NOT EXISTS app_v3.organization_group_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id integer NOT NULL REFERENCES app_v3.organization_groups(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES app_v3.profiles(id) ON DELETE CASCADE,
  role app_v3."OrganizationMemberRole" NOT NULL,
  role_pack app_v3."OrganizationRolePack",
  scope_all_orgs boolean NOT NULL DEFAULT false,
  scope_org_ids integer[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS organization_group_members_group_user_uniq
  ON app_v3.organization_group_members (group_id, user_id);

CREATE INDEX IF NOT EXISTS organization_group_members_group_idx
  ON app_v3.organization_group_members (group_id);

CREATE INDEX IF NOT EXISTS organization_group_members_user_idx
  ON app_v3.organization_group_members (user_id);

CREATE TABLE IF NOT EXISTS app_v3.organization_member_overrides (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  group_member_id uuid NOT NULL REFERENCES app_v3.organization_group_members(id) ON DELETE CASCADE,
  organization_id integer NOT NULL REFERENCES app_v3.organizations(id) ON DELETE CASCADE,
  role_override app_v3."OrganizationMemberRole",
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS organization_member_overrides_group_org_uniq
  ON app_v3.organization_member_overrides (group_member_id, organization_id);

CREATE INDEX IF NOT EXISTS organization_member_overrides_org_idx
  ON app_v3.organization_member_overrides (organization_id);

INSERT INTO app_v3.organization_group_members (
  group_id,
  user_id,
  role,
  role_pack,
  scope_all_orgs,
  scope_org_ids,
  created_at,
  updated_at
)
SELECT o.group_id,
       m.user_id,
       m.role,
       m.role_pack,
       false,
       ARRAY[m.organization_id],
       COALESCE(m.created_at, now()),
       COALESCE(m.updated_at, now())
FROM app_v3.organization_members m
JOIN app_v3.organizations o ON o.id = m.organization_id
ON CONFLICT (group_id, user_id) DO NOTHING;
