BEGIN;

CREATE TABLE IF NOT EXISTS app_v3.refund_policy_versions (
  env text NOT NULL DEFAULT 'prod',
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  organization_id integer NOT NULL,
  event_id integer,
  policy_version text NOT NULL,
  fee_bps integer NOT NULL DEFAULT 0,
  fee_fixed_cents integer NOT NULL DEFAULT 0,
  fee_payer app_v3."RefundFeePayer" NOT NULL DEFAULT 'CUSTOMER',
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  created_by_user_id uuid,
  CONSTRAINT refund_policy_versions_pkey PRIMARY KEY (id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'refund_policy_versions_organization_id_fkey'
      AND connamespace = 'app_v3'::regnamespace
  ) THEN
    ALTER TABLE app_v3.refund_policy_versions
      ADD CONSTRAINT refund_policy_versions_organization_id_fkey
      FOREIGN KEY (organization_id)
      REFERENCES app_v3.organizations(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'refund_policy_versions_event_id_fkey'
      AND connamespace = 'app_v3'::regnamespace
  ) THEN
    ALTER TABLE app_v3.refund_policy_versions
      ADD CONSTRAINT refund_policy_versions_event_id_fkey
      FOREIGN KEY (event_id)
      REFERENCES app_v3.events(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'refund_policy_versions_org_event_version_uq'
      AND connamespace = 'app_v3'::regnamespace
  ) THEN
    ALTER TABLE app_v3.refund_policy_versions
      ADD CONSTRAINT refund_policy_versions_org_event_version_uq
      UNIQUE (organization_id, event_id, policy_version);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS refund_policy_versions_org_event_idx
  ON app_v3.refund_policy_versions (organization_id, event_id);

CREATE TABLE IF NOT EXISTS app_v3.padel_tournament_roles (
  env text NOT NULL DEFAULT 'prod',
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  event_id integer NOT NULL,
  organization_id integer NOT NULL,
  user_id uuid NOT NULL,
  role app_v3."PadelTournamentRole" NOT NULL,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT padel_tournament_roles_pkey PRIMARY KEY (id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'padel_tournament_roles_event_id_fkey'
      AND connamespace = 'app_v3'::regnamespace
  ) THEN
    ALTER TABLE app_v3.padel_tournament_roles
      ADD CONSTRAINT padel_tournament_roles_event_id_fkey
      FOREIGN KEY (event_id)
      REFERENCES app_v3.events(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'padel_tournament_roles_organization_id_fkey'
      AND connamespace = 'app_v3'::regnamespace
  ) THEN
    ALTER TABLE app_v3.padel_tournament_roles
      ADD CONSTRAINT padel_tournament_roles_organization_id_fkey
      FOREIGN KEY (organization_id)
      REFERENCES app_v3.organizations(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'padel_tournament_roles_user_id_fkey'
      AND connamespace = 'app_v3'::regnamespace
  ) THEN
    ALTER TABLE app_v3.padel_tournament_roles
      ADD CONSTRAINT padel_tournament_roles_user_id_fkey
      FOREIGN KEY (user_id)
      REFERENCES app_v3.profiles(id)
      ON DELETE CASCADE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'padel_tournament_roles_event_role_user_uq'
      AND connamespace = 'app_v3'::regnamespace
  ) THEN
    ALTER TABLE app_v3.padel_tournament_roles
      ADD CONSTRAINT padel_tournament_roles_event_role_user_uq
      UNIQUE (event_id, role, user_id);
  END IF;
END
$$;

CREATE INDEX IF NOT EXISTS padel_tournament_roles_event_idx
  ON app_v3.padel_tournament_roles (event_id);
CREATE INDEX IF NOT EXISTS padel_tournament_roles_org_idx
  ON app_v3.padel_tournament_roles (organization_id);
CREATE INDEX IF NOT EXISTS padel_tournament_roles_user_idx
  ON app_v3.padel_tournament_roles (user_id);

COMMIT;
