DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'BookingSplitOffsessionAttemptStatus'
      AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."BookingSplitOffsessionAttemptStatus" AS ENUM (
      'SUCCEEDED',
      'FAILED_RETRYABLE',
      'FAILED_FINAL',
      'SKIPPED_NO_PAYMENT_METHOD'
    );
  END IF;
END$$;

ALTER TABLE app_v3.booking_split_participants
  ADD COLUMN IF NOT EXISTS offsession_payment_method_id text,
  ADD COLUMN IF NOT EXISTS offsession_customer_id text;

CREATE INDEX IF NOT EXISTS booking_split_participants_offsession_pm_idx
  ON app_v3.booking_split_participants (offsession_payment_method_id);

CREATE TABLE IF NOT EXISTS app_v3.booking_split_offsession_attempts (
  env text NOT NULL DEFAULT 'prod',
  id integer GENERATED BY DEFAULT AS IDENTITY,
  split_id integer NOT NULL,
  participant_id integer NOT NULL,
  attempt_no integer NOT NULL,
  status app_v3."BookingSplitOffsessionAttemptStatus" NOT NULL,
  payment_intent_id text,
  error_code text,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT booking_split_offsession_attempts_pkey PRIMARY KEY (id),
  CONSTRAINT booking_split_offsession_attempts_split_fk
    FOREIGN KEY (split_id) REFERENCES app_v3.booking_splits(id)
    ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_split_offsession_attempts_participant_fk
    FOREIGN KEY (participant_id) REFERENCES app_v3.booking_split_participants(id)
    ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE UNIQUE INDEX IF NOT EXISTS booking_split_offsession_attempts_unique
  ON app_v3.booking_split_offsession_attempts (split_id, participant_id, attempt_no);

CREATE INDEX IF NOT EXISTS booking_split_offsession_attempts_split_idx
  ON app_v3.booking_split_offsession_attempts (split_id);

CREATE INDEX IF NOT EXISTS booking_split_offsession_attempts_participant_idx
  ON app_v3.booking_split_offsession_attempts (participant_id);

CREATE INDEX IF NOT EXISTS booking_split_offsession_attempts_status_idx
  ON app_v3.booking_split_offsession_attempts (status);

UPDATE app_v3.booking_splits
SET split_mode = 'SPLIT_GARANTIDO'
WHERE status = 'OPEN'
  AND split_mode <> 'SPLIT_GARANTIDO';

UPDATE app_v3.booking_splits
SET rail_state = 'HOLD_CAPTURE'
WHERE status = 'OPEN'
  AND rail_state IS NULL;

UPDATE app_v3.booking_splits
SET capture_before_at = CASE
    WHEN deadline_at IS NOT NULL THEN deadline_at - interval '30 minutes'
    ELSE now() + interval '30 minutes'
  END,
  capture_before_source = 'CANONICAL_COMPUTED_TABLE'
WHERE status = 'OPEN'
  AND capture_before_at IS NULL;

UPDATE app_v3.booking_splits
SET retry_until_at = GREATEST(
    now() + interval '2 hours',
    COALESCE(deadline_at + interval '2 hours', now() + interval '2 hours'),
    COALESCE(capture_before_at + interval '2 hours', now() + interval '2 hours')
  )
WHERE status = 'OPEN'
  AND retry_until_at IS NULL;
