DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'BookingSplitCancelReason' AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."BookingSplitCancelReason" AS ENUM (
      'USER_REQUESTED',
      'TARGET_UPDATED',
      'GUARANTEE_LOST'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'BookingSplitShareAttemptStatus' AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."BookingSplitShareAttemptStatus" AS ENUM (
      'OPEN',
      'REQUIRES_ACTION',
      'SUCCEEDED',
      'FAILED',
      'CANCELLED'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'BookingSplitShareAttemptFailureClass' AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."BookingSplitShareAttemptFailureClass" AS ENUM (
      'AUTH_REQUIRED',
      'INSUFFICIENT_FUNDS',
      'PROCESSOR_ERROR',
      'INVALID_PAYMENT_METHOD',
      'UNKNOWN'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'BookingSplitHoldAttemptStatus' AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."BookingSplitHoldAttemptStatus" AS ENUM (
      'SUCCEEDED',
      'FAILED_RETRYABLE',
      'FAILED_FINAL'
    );
  END IF;
END $$;

ALTER TABLE app_v3.booking_splits
  ADD COLUMN IF NOT EXISTS cancel_reason app_v3."BookingSplitCancelReason";

ALTER TABLE app_v3.booking_split_participants
  ADD COLUMN IF NOT EXISTS active_share_attempt_id integer;

CREATE TABLE IF NOT EXISTS app_v3.booking_split_share_attempts (
  env text NOT NULL DEFAULT 'prod',
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  participant_id integer NOT NULL,
  attempt_no integer NOT NULL,
  status app_v3."BookingSplitShareAttemptStatus" NOT NULL,
  failure_class app_v3."BookingSplitShareAttemptFailureClass",
  payment_id text,
  payment_intent_id text,
  action_expire_at timestamptz(6),
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT booking_split_share_attempts_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS app_v3.booking_split_hold_attempts (
  env text NOT NULL DEFAULT 'prod',
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  split_id integer NOT NULL,
  attempt_no integer NOT NULL,
  status app_v3."BookingSplitHoldAttemptStatus" NOT NULL,
  previous_capture_before_at timestamptz(6),
  next_capture_before_at timestamptz(6),
  error_code text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT booking_split_hold_attempts_pkey PRIMARY KEY (id)
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_schema = 'app_v3'
      AND table_name = 'booking_split_share_attempts'
      AND constraint_name = 'booking_split_share_attempts_participant_fkey'
  ) THEN
    ALTER TABLE app_v3.booking_split_share_attempts
      ADD CONSTRAINT booking_split_share_attempts_participant_fkey
      FOREIGN KEY (participant_id)
      REFERENCES app_v3.booking_split_participants(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_schema = 'app_v3'
      AND table_name = 'booking_split_hold_attempts'
      AND constraint_name = 'booking_split_hold_attempts_split_fkey'
  ) THEN
    ALTER TABLE app_v3.booking_split_hold_attempts
      ADD CONSTRAINT booking_split_hold_attempts_split_fkey
      FOREIGN KEY (split_id)
      REFERENCES app_v3.booking_splits(id)
      ON DELETE CASCADE
      ON UPDATE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.table_constraints
    WHERE table_schema = 'app_v3'
      AND table_name = 'booking_split_participants'
      AND constraint_name = 'booking_split_participants_active_share_attempt_fkey'
  ) THEN
    ALTER TABLE app_v3.booking_split_participants
      ADD CONSTRAINT booking_split_participants_active_share_attempt_fkey
      FOREIGN KEY (active_share_attempt_id)
      REFERENCES app_v3.booking_split_share_attempts(id)
      ON DELETE SET NULL
      ON UPDATE CASCADE;
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS booking_split_share_attempts_participant_attempt_no_unique
  ON app_v3.booking_split_share_attempts (participant_id, attempt_no);

CREATE INDEX IF NOT EXISTS booking_split_share_attempts_participant_idx
  ON app_v3.booking_split_share_attempts (participant_id);

CREATE INDEX IF NOT EXISTS booking_split_share_attempts_status_idx
  ON app_v3.booking_split_share_attempts (status);

CREATE UNIQUE INDEX IF NOT EXISTS booking_split_hold_attempts_split_attempt_no_unique
  ON app_v3.booking_split_hold_attempts (split_id, attempt_no);

CREATE INDEX IF NOT EXISTS booking_split_hold_attempts_split_idx
  ON app_v3.booking_split_hold_attempts (split_id);

CREATE INDEX IF NOT EXISTS booking_split_hold_attempts_status_idx
  ON app_v3.booking_split_hold_attempts (status);

CREATE INDEX IF NOT EXISTS booking_split_participants_active_share_attempt_idx
  ON app_v3.booking_split_participants (active_share_attempt_id);
