BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'app_v3'
      AND t.typname = 'PadelRankingSnapshotMode'
  ) THEN
    CREATE TYPE app_v3."PadelRankingSnapshotMode" AS ENUM ('START', 'CURRENT');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS app_v3.padel_global_rating_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  env text NOT NULL DEFAULT 'prod',
  user_id uuid NOT NULL,
  rating double precision NOT NULL DEFAULT 1200,
  rd double precision NOT NULL DEFAULT 350,
  sigma double precision NOT NULL DEFAULT 0.06,
  tau double precision NOT NULL DEFAULT 0.5,
  matches_played integer NOT NULL DEFAULT 0,
  leaderboard_eligible boolean NOT NULL DEFAULT true,
  blocked_new_matches boolean NOT NULL DEFAULT false,
  suspension_ends_at timestamptz(6),
  last_match_at timestamptz(6),
  last_activity_at timestamptz(6),
  last_rebuild_at timestamptz(6),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  updated_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT padel_global_rating_profiles_user_uq UNIQUE (user_id),
  CONSTRAINT padel_global_rating_profiles_user_fk FOREIGN KEY (user_id)
    REFERENCES app_v3.profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS padel_global_rating_profiles_rating_idx
  ON app_v3.padel_global_rating_profiles(rating);
CREATE INDEX IF NOT EXISTS padel_global_rating_profiles_leaderboard_idx
  ON app_v3.padel_global_rating_profiles(leaderboard_eligible);

CREATE TABLE IF NOT EXISTS app_v3.padel_global_rating_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  env text NOT NULL DEFAULT 'prod',
  user_id uuid NOT NULL,
  organization_id integer,
  event_id integer,
  match_id integer,
  tier text,
  club_id integer,
  city text,
  opponent_avg_rating double precision,
  pre_rating double precision NOT NULL,
  pre_rd double precision NOT NULL,
  pre_sigma double precision NOT NULL,
  post_rating double precision NOT NULL,
  post_rd double precision NOT NULL,
  post_sigma double precision NOT NULL,
  expected_score double precision,
  actual_score double precision,
  games_for integer,
  games_against integer,
  tier_multiplier double precision NOT NULL DEFAULT 1,
  carry_multiplier double precision NOT NULL DEFAULT 1,
  metadata jsonb DEFAULT '{}'::jsonb,
  occurred_at timestamptz(6) NOT NULL,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT padel_global_rating_events_user_fk FOREIGN KEY (user_id)
    REFERENCES app_v3.profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT padel_global_rating_events_org_fk FOREIGN KEY (organization_id)
    REFERENCES app_v3.organizations(id) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT padel_global_rating_events_event_fk FOREIGN KEY (event_id)
    REFERENCES app_v3.events(id) ON DELETE SET NULL ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS padel_global_rating_events_org_idx
  ON app_v3.padel_global_rating_events(organization_id);
CREATE INDEX IF NOT EXISTS padel_global_rating_events_event_idx
  ON app_v3.padel_global_rating_events(event_id);
CREATE INDEX IF NOT EXISTS padel_global_rating_events_match_idx
  ON app_v3.padel_global_rating_events(match_id);
CREATE INDEX IF NOT EXISTS padel_global_rating_events_org_tier_idx
  ON app_v3.padel_global_rating_events(organization_id, tier);
CREATE INDEX IF NOT EXISTS padel_global_rating_events_org_club_idx
  ON app_v3.padel_global_rating_events(organization_id, club_id);
CREATE INDEX IF NOT EXISTS padel_global_rating_events_org_city_idx
  ON app_v3.padel_global_rating_events(organization_id, city);
CREATE INDEX IF NOT EXISTS padel_global_rating_events_user_occurred_idx
  ON app_v3.padel_global_rating_events(user_id, occurred_at);

CREATE TABLE IF NOT EXISTS app_v3.padel_event_ranking_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  env text NOT NULL DEFAULT 'prod',
  organization_id integer NOT NULL,
  event_id integer NOT NULL,
  user_id uuid NOT NULL,
  player_id integer,
  snapshot_mode app_v3."PadelRankingSnapshotMode" NOT NULL DEFAULT 'START',
  rating double precision NOT NULL,
  points integer NOT NULL DEFAULT 0,
  global_position integer,
  organization_position integer,
  occurred_at timestamptz(6) NOT NULL,
  created_at timestamptz(6) NOT NULL DEFAULT now(),
  CONSTRAINT padel_event_ranking_snapshot_event_user_mode_uq UNIQUE (event_id, user_id, snapshot_mode),
  CONSTRAINT padel_event_ranking_snapshot_org_fk FOREIGN KEY (organization_id)
    REFERENCES app_v3.organizations(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT padel_event_ranking_snapshot_event_fk FOREIGN KEY (event_id)
    REFERENCES app_v3.events(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT padel_event_ranking_snapshot_user_fk FOREIGN KEY (user_id)
    REFERENCES app_v3.profiles(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT padel_event_ranking_snapshot_player_fk FOREIGN KEY (player_id)
    REFERENCES app_v3.padel_player_profiles(id) ON DELETE SET NULL ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS padel_event_ranking_snapshot_org_idx
  ON app_v3.padel_event_ranking_snapshots(organization_id);
CREATE INDEX IF NOT EXISTS padel_event_ranking_snapshot_event_idx
  ON app_v3.padel_event_ranking_snapshots(event_id);
CREATE INDEX IF NOT EXISTS padel_event_ranking_snapshot_mode_idx
  ON app_v3.padel_event_ranking_snapshots(snapshot_mode);
CREATE INDEX IF NOT EXISTS padel_event_ranking_snapshot_global_pos_idx
  ON app_v3.padel_event_ranking_snapshots(global_position);
CREATE INDEX IF NOT EXISTS padel_event_ranking_snapshot_org_pos_idx
  ON app_v3.padel_event_ranking_snapshots(organization_position);

COMMIT;
