-- D15 Macro + Micro Analytics (derivado do Ledger)

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'AnalyticsMetricKey' AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."AnalyticsMetricKey" AS ENUM (
      'GROSS',
      'PLATFORM_FEES',
      'PROCESSOR_FEES',
      'NET_TO_ORG'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE t.typname = 'AnalyticsDimensionKey' AND n.nspname = 'app_v3'
  ) THEN
    CREATE TYPE app_v3."AnalyticsDimensionKey" AS ENUM (
      'MODULE',
      'SOURCE_TYPE',
      'PAYMENT_PROVIDER',
      'CURRENCY'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS app_v3.analytics_rollups (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  organization_id integer NOT NULL REFERENCES app_v3.organizations(id) ON DELETE CASCADE,
  bucket_date date NOT NULL,
  metric_key app_v3."AnalyticsMetricKey" NOT NULL,
  dimension_key app_v3."AnalyticsDimensionKey" NOT NULL,
  dimension_value text NOT NULL,
  value integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS analytics_rollup_unique
  ON app_v3.analytics_rollups (organization_id, bucket_date, metric_key, dimension_key, dimension_value);

CREATE INDEX IF NOT EXISTS analytics_rollup_org_bucket_idx
  ON app_v3.analytics_rollups (organization_id, bucket_date);
