import fs from "fs";
import path from "path";

const ROOT = process.cwd();
const APP_ROOT = path.join(ROOT, "app");
const OUTPUT_PATH = path.join(ROOT, "packages", "shared", "src", "reservedUsernames.generated.ts");
const PUBLIC_ROOT = path.join(ROOT, "public");

const ROUTE_FILE_REGEX = /[\\/](page|route)\.(ts|tsx|js|jsx)$/;
const IGNORED_SEGMENTS = new Set(["_components", "_lib", "_explorar"]);

function listFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...listFiles(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

function listPublicEntries() {
  if (!fs.existsSync(PUBLIC_ROOT)) return [];
  const entries = fs.readdirSync(PUBLIC_ROOT, { withFileTypes: true });
  const names: string[] = [];
  for (const entry of entries) {
    if (entry.name === ".DS_Store") continue;
    names.push(entry.name);
  }
  return names.sort((a, b) => a.localeCompare(b));
}

function isValidSegment(segment: string) {
  if (!segment) return false;
  if (segment.startsWith("[")) return false;
  if (segment.startsWith("_")) return false;
  if (segment.startsWith("(")) return false;
  if (IGNORED_SEGMENTS.has(segment)) return false;
  return true;
}

function extractRouteSegments() {
  const files = listFiles(APP_ROOT);
  const segments = new Set<string>();

  for (const file of files) {
    if (!ROUTE_FILE_REGEX.test(file)) continue;
    const rel = path.relative(APP_ROOT, file);
    const parts = rel.split(path.sep);
    if (parts.length < 2) continue;
    const dirParts = parts.slice(0, -1);
    const firstSegment = dirParts.find((segment) => isValidSegment(segment));
    if (!firstSegment) continue;
    segments.add(firstSegment);
  }

  return Array.from(segments).sort((a, b) => a.localeCompare(b));
}

function formatArray(values: string[]) {
  if (values.length === 0) return "[] as const";
  return `[\n${values.map((v) => `  "${v}"`).join(",\n")}\n] as const`;
}

function writeOutput(segments: string[], publicEntries: string[]) {
  const content = `// This file is auto-generated by scripts/generate-reserved-usernames.ts
// Do not edit by hand.

export const ROUTE_SEGMENTS = ${formatArray(segments)};
export const PUBLIC_ENTRIES = ${formatArray(publicEntries)};
`;
  fs.writeFileSync(OUTPUT_PATH, content, "utf8");
}

const segments = extractRouteSegments();
const publicEntries = listPublicEntries();
writeOutput(segments, publicEntries);
console.log(
  `[reserved-usernames] wrote ${segments.length} segments and ${publicEntries.length} public entries to ${OUTPUT_PATH}`,
);
