-- Service packages + booking package snapshot

CREATE TABLE IF NOT EXISTS app_v3.service_packages (
  env text NOT NULL DEFAULT 'prod',
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  service_id integer NOT NULL,
  label text NOT NULL,
  description text,
  duration_minutes integer NOT NULL,
  price_cents integer NOT NULL,
  recommended boolean NOT NULL DEFAULT false,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT service_packages_service_fk
    FOREIGN KEY (service_id) REFERENCES app_v3.services(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS service_packages_service_idx ON app_v3.service_packages(service_id);
CREATE INDEX IF NOT EXISTS service_packages_active_idx ON app_v3.service_packages(is_active);
CREATE INDEX IF NOT EXISTS service_packages_sort_idx ON app_v3.service_packages(sort_order);
CREATE INDEX IF NOT EXISTS service_packages_env_idx ON app_v3.service_packages(env);

CREATE TABLE IF NOT EXISTS app_v3.booking_packages (
  env text NOT NULL DEFAULT 'prod',
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  booking_id integer NOT NULL UNIQUE,
  package_id integer,
  label text NOT NULL,
  duration_minutes integer NOT NULL,
  price_cents integer NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT booking_packages_booking_fk
    FOREIGN KEY (booking_id) REFERENCES app_v3.bookings(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_packages_package_fk
    FOREIGN KEY (package_id) REFERENCES app_v3.service_packages(id) ON DELETE SET NULL ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS booking_packages_booking_idx ON app_v3.booking_packages(booking_id);
CREATE INDEX IF NOT EXISTS booking_packages_package_idx ON app_v3.booking_packages(package_id);
CREATE INDEX IF NOT EXISTS booking_packages_env_idx ON app_v3.booking_packages(env);

-- RLS env isolation for new tables
ALTER TABLE app_v3.service_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_v3.booking_packages ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'app_v3' AND tablename = 'service_packages' AND policyname = 'env_isolation'
  ) THEN
    CREATE POLICY env_isolation ON app_v3.service_packages
      USING (env = current_setting('app.env', true))
      WITH CHECK (env = current_setting('app.env', true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'app_v3' AND tablename = 'booking_packages' AND policyname = 'env_isolation'
  ) THEN
    CREATE POLICY env_isolation ON app_v3.booking_packages
      USING (env = current_setting('app.env', true))
      WITH CHECK (env = current_setting('app.env', true));
  END IF;
END $$;
