-- Service add-ons + booking add-on snapshots

CREATE TABLE IF NOT EXISTS app_v3.service_addons (
  env text NOT NULL DEFAULT 'prod',
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  service_id integer NOT NULL,
  label text NOT NULL,
  description text,
  delta_minutes integer NOT NULL DEFAULT 0,
  delta_price_cents integer NOT NULL DEFAULT 0,
  max_qty integer,
  category text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT service_addons_service_fk
    FOREIGN KEY (service_id) REFERENCES app_v3.services(id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS service_addons_service_idx ON app_v3.service_addons(service_id);
CREATE INDEX IF NOT EXISTS service_addons_active_idx ON app_v3.service_addons(is_active);
CREATE INDEX IF NOT EXISTS service_addons_sort_idx ON app_v3.service_addons(sort_order);
CREATE INDEX IF NOT EXISTS service_addons_env_idx ON app_v3.service_addons(env);

CREATE TABLE IF NOT EXISTS app_v3.booking_addons (
  env text NOT NULL DEFAULT 'prod',
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  booking_id integer NOT NULL,
  addon_id integer,
  label text NOT NULL,
  delta_minutes integer NOT NULL DEFAULT 0,
  delta_price_cents integer NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT booking_addons_booking_fk
    FOREIGN KEY (booking_id) REFERENCES app_v3.bookings(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT booking_addons_addon_fk
    FOREIGN KEY (addon_id) REFERENCES app_v3.service_addons(id) ON DELETE SET NULL ON UPDATE NO ACTION
);

CREATE INDEX IF NOT EXISTS booking_addons_booking_idx ON app_v3.booking_addons(booking_id);
CREATE INDEX IF NOT EXISTS booking_addons_addon_idx ON app_v3.booking_addons(addon_id);
CREATE INDEX IF NOT EXISTS booking_addons_env_idx ON app_v3.booking_addons(env);

-- RLS env isolation for new tables
ALTER TABLE app_v3.service_addons ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_v3.booking_addons ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'app_v3' AND tablename = 'service_addons' AND policyname = 'env_isolation'
  ) THEN
    CREATE POLICY env_isolation ON app_v3.service_addons
      USING (env = current_setting('app.env', true))
      WITH CHECK (env = current_setting('app.env', true));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'app_v3' AND tablename = 'booking_addons' AND policyname = 'env_isolation'
  ) THEN
    CREATE POLICY env_isolation ON app_v3.booking_addons
      USING (env = current_setting('app.env', true))
      WITH CHECK (env = current_setting('app.env', true));
  END IF;
END $$;
