-- Schedule delays (estimated start overlays)

CREATE TABLE IF NOT EXISTS app_v3.schedule_delays (
  env text NOT NULL DEFAULT 'prod',
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  organization_id integer NOT NULL,
  scope_type app_v3."AvailabilityScopeType" NOT NULL,
  scope_id integer NOT NULL DEFAULT 0,
  delay_minutes integer NOT NULL DEFAULT 0,
  reason text,
  effective_from timestamptz NOT NULL DEFAULT now(),
  created_by_user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT schedule_delays_org_fk
    FOREIGN KEY (organization_id) REFERENCES app_v3.organizations(id) ON DELETE CASCADE ON UPDATE NO ACTION,
  CONSTRAINT schedule_delays_created_by_fk
    FOREIGN KEY (created_by_user_id) REFERENCES app_v3.profiles(id) ON DELETE SET NULL ON UPDATE NO ACTION,
  CONSTRAINT schedule_delays_minutes_chk CHECK (delay_minutes >= 0)
);

CREATE INDEX IF NOT EXISTS schedule_delays_org_scope_idx
  ON app_v3.schedule_delays(organization_id, scope_type, scope_id);
CREATE INDEX IF NOT EXISTS schedule_delays_org_effective_idx
  ON app_v3.schedule_delays(organization_id, effective_from DESC);
CREATE INDEX IF NOT EXISTS schedule_delays_env_idx
  ON app_v3.schedule_delays(env);

ALTER TABLE app_v3.schedule_delays ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'app_v3' AND tablename = 'schedule_delays' AND policyname = 'env_isolation'
  ) THEN
    CREATE POLICY env_isolation ON app_v3.schedule_delays
      USING (env = current_setting('app.env', true))
      WITH CHECK (env = current_setting('app.env', true));
  END IF;
END $$;
