AWSTemplateFormatVersion: "2010-09-09"
Description: ORYA prod ECS/Fargate + ECR + ALB + EventBridge (skeleton)

Parameters:
  EnvironmentName:
    Type: String
    Default: prod
  VpcId:
    Type: AWS::EC2::VPC::Id
  PublicSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  PrivateSubnets:
    Type: List<AWS::EC2::Subnet::Id>
  AlbCertificateArn:
    Type: String
    Description: ACM certificate ARN for app.orya.pt
  WebImage:
    Type: String
    Description: ECR image URI for web (e.g. 495219734037.dkr.ecr.eu-west-1.amazonaws.com/orya-web:latest)
  WorkerImage:
    Type: String
    Description: ECR image URI for worker (e.g. 495219734037.dkr.ecr.eu-west-1.amazonaws.com/orya-worker:latest)
  WebDesiredCount:
    Type: Number
    Default: 2
  WorkerDesiredCount:
    Type: Number
    Default: 1
  TaskCpu:
    Type: String
    Default: "512"
  TaskMemory:
    Type: String
    Default: "1024"
  LogsRetentionDays:
    Type: Number
    Default: 30
  HealthCheckPath:
    Type: String
    Default: /api/internal/health
  OutboxSchedule:
    Type: String
    Default: rate(1 minute)

Resources:
  EcrRepoWeb:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: orya-web
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": { "type": "expire" }
              }
            ]
          }
  EcrRepoWorker:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: orya-worker
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep last 20 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 20
                },
                "action": { "type": "expire" }
              }
            ]
          }

  LogGroupWeb:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/orya/${EnvironmentName}/web"
      RetentionInDays: !Ref LogsRetentionDays
  LogGroupWorker:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/ecs/orya/${EnvironmentName}/worker"
      RetentionInDays: !Ref LogsRetentionDays

  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "orya-${EnvironmentName}"
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ORYA ALB SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ORYA ECS Service SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "orya-${EnvironmentName}-alb"
      Scheme: internet-facing
      Type: application
      Subnets: !Ref PublicSubnets
      SecurityGroups:
        - !Ref ALBSecurityGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "orya-${EnvironmentName}-tg"
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckEnabled: true
      HealthCheckPath: !Ref HealthCheckPath
      Matcher:
        HttpCode: "200-399"

  Listener443:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !Ref AlbCertificateArn
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: orya-ecs-exec-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: orya-ecs-exec-secrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/*"

  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: orya-ecs-task-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: orya-ecs-task-secrets
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: "arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  WebTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: orya-web
      RequiresCompatibilities: [FARGATE]
      NetworkMode: awsvpc
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: orya-web
          Image: !Ref WebImage
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: production
          Secrets:
            - Name: DATABASE_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/DATABASE_URL
            - Name: DIRECT_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/DIRECT_URL
            - Name: SUPABASE_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/SUPABASE_URL
            - Name: SUPABASE_SERVICE_ROLE
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/SUPABASE_SERVICE_ROLE
            - Name: SUPABASE_ANON_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/SUPABASE_ANON_KEY
            - Name: STRIPE_SECRET_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/STRIPE_SECRET_KEY
            - Name: STRIPE_WEBHOOK_SECRET
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/STRIPE_WEBHOOK_SECRET
            - Name: RESEND_API_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/RESEND_API_KEY
            - Name: RESEND_FROM_EMAIL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/RESEND_FROM_EMAIL
            - Name: SENTRY_DSN
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/SENTRY_DSN
            - Name: ORYA_CRON_SECRET
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/ORYA_CRON_SECRET
            - Name: QR_SECRET_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/QR_SECRET_KEY
            - Name: APP_BASE_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APP_BASE_URL
            - Name: NEXT_PUBLIC_BASE_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/NEXT_PUBLIC_BASE_URL
            - Name: NEXT_PUBLIC_SUPABASE_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/NEXT_PUBLIC_SUPABASE_URL
            - Name: NEXT_PUBLIC_SUPABASE_ANON_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/NEXT_PUBLIC_SUPABASE_ANON_KEY
            - Name: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
            - Name: APPLE_SIGNIN_SERVICE_ID
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APPLE_SIGNIN_SERVICE_ID
            - Name: APPLE_SIGNIN_REDIRECT_URI
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APPLE_SIGNIN_REDIRECT_URI
            - Name: APPLE_SIGNIN_TEAM_ID
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APPLE_SIGNIN_TEAM_ID
            - Name: APPLE_SIGNIN_KEY_ID
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APPLE_SIGNIN_KEY_ID
            - Name: APPLE_SIGNIN_PRIVATE_KEY_BASE64
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APPLE_SIGNIN_PRIVATE_KEY_BASE64
            - Name: APNS_TEAM_ID
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APNS_TEAM_ID
            - Name: APNS_KEY_ID
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APNS_KEY_ID
            - Name: APNS_PRIVATE_KEY_BASE64
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APNS_PRIVATE_KEY_BASE64
            - Name: APNS_TOPIC
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/APNS_TOPIC
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroupWeb
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - "curl -sf -H 'x-orya-cron-secret: ${ORYA_CRON_SECRET}' http://localhost:3000${HealthCheckPath} || exit 1"
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60

  WorkerTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: orya-worker
      RequiresCompatibilities: [FARGATE]
      NetworkMode: awsvpc
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt ECSTaskRole.Arn
      ContainerDefinitions:
        - Name: orya-worker
          Image: !Ref WorkerImage
          Command: ["node", "scripts/operations-loop.js"]
          Environment:
            - Name: NODE_ENV
              Value: production
          Secrets:
            - Name: DATABASE_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/DATABASE_URL
            - Name: DIRECT_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/DIRECT_URL
            - Name: SUPABASE_URL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/SUPABASE_URL
            - Name: SUPABASE_SERVICE_ROLE
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/SUPABASE_SERVICE_ROLE
            - Name: SUPABASE_ANON_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/SUPABASE_ANON_KEY
            - Name: STRIPE_SECRET_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/STRIPE_SECRET_KEY
            - Name: STRIPE_WEBHOOK_SECRET
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/STRIPE_WEBHOOK_SECRET
            - Name: RESEND_API_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/RESEND_API_KEY
            - Name: RESEND_FROM_EMAIL
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/RESEND_FROM_EMAIL
            - Name: SENTRY_DSN
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/SENTRY_DSN
            - Name: ORYA_CRON_SECRET
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/ORYA_CRON_SECRET
            - Name: QR_SECRET_KEY
              ValueFrom: arn:aws:secretsmanager:eu-west-1:495219734037:secret:orya/prod/QR_SECRET_KEY
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroupWorker
              awslogs-region: eu-west-1
              awslogs-stream-prefix: ecs

  WebService:
    Type: AWS::ECS::Service
    DependsOn: Listener443
    Properties:
      ServiceName: !Sub "orya-${EnvironmentName}-web"
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref WebDesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref WebTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PrivateSubnets
          SecurityGroups:
            - !Ref ServiceSecurityGroup
      LoadBalancers:
        - ContainerName: orya-web
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroup
      DeploymentConfiguration:
        MinimumHealthyPercent: 50
        MaximumPercent: 200

  WorkerService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub "orya-${EnvironmentName}-worker"
      Cluster: !Ref ECSCluster
      DesiredCount: !Ref WorkerDesiredCount
      CapacityProviderStrategy:
        - CapacityProvider: FARGATE_SPOT
          Weight: 2
        - CapacityProvider: FARGATE
          Weight: 1
      TaskDefinition: !Ref WorkerTaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref PrivateSubnets
          SecurityGroups:
            - !Ref ServiceSecurityGroup

  EventsRunTaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: orya-eventbridge-run-task
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: orya-run-task
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt ECSTaskExecutionRole.Arn
                  - !GetAtt ECSTaskRole.Arn

  OutboxScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "orya-${EnvironmentName}-outbox"
      ScheduleExpression: !Ref OutboxSchedule
      State: ENABLED
      Targets:
        - Arn: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ECSCluster}"
          RoleArn: !GetAtt EventsRunTaskRole.Arn
          Id: outbox-run-task
          EcsParameters:
            TaskDefinitionArn: !Ref WorkerTaskDefinition
            TaskCount: 1
            LaunchType: FARGATE
            NetworkConfiguration:
              AwsVpcConfiguration:
                Subnets: !Ref PrivateSubnets
                SecurityGroups:
                  - !Ref ServiceSecurityGroup
                AssignPublicIp: ENABLED

Outputs:
  ClusterName:
    Value: !Ref ECSCluster
  WebServiceName:
    Value: !Ref WebService
  WorkerServiceName:
    Value: !Ref WorkerService
  LoadBalancerDNS:
    Value: !GetAtt LoadBalancer.DNSName
