AWSTemplateFormatVersion: "2010-09-09"
Description: ORYA prod ACM certificate + Route53 validation (skeleton)

Parameters:
  HostedZoneId:
    Type: String
    Description: Route53 hosted zone ID
  DomainName:
    Type: String
    Default: app.orya.pt

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

Outputs:
  CertificateArn:
    Value: !Ref Certificate
